"""initial migration

Revision ID: 0e8b8b1a6e04
Revises:
Create Date: 2026-06-12 15:39:31.710472

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e8b8b1a6e04"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_area", sa.Text(), nullable=True),
        sa.Column("owner_person", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_key"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=100), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum("MANUAL_UPLOAD", "HTTP_FILE", "API_JSON", name="sourcetype"),
            nullable=False,
        ),
        sa.Column(
            "ingestion_mode",
            sa.Enum("MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode"),
            nullable=False,
        ),
        sa.Column("manual_upload_allowed", sa.Boolean(), nullable=False),
        sa.Column("requires_manifest", sa.Boolean(), nullable=False),
        sa.Column("expected_file_types", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "period_type",
            sa.Enum(
                "DAILY", "WEEKLY", "MONTHLY", "QUARTERLY", "YEARLY", "CUSTOM", name="periodtype"
            ),
            nullable=True,
        ),
        sa.Column("schedule", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sources_product_key", "sources", ["product_id", "source_key"], unique=True)
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=100), nullable=False),
        sa.Column("period_label", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "DUPLICATED",
                "REJECTED",
                "PARTIAL",
                name="runstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "ingestion_mode",
            sa.Enum("MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode"),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            sa.Enum(
                "SCHEDULED",
                "MANUAL_AIRFLOW",
                "MANUAL_DROPZONE",
                "MANUAL_CLI",
                "BACKFILL",
                "RETRY",
                name="triggertype",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("airflow_dag_id", sa.String(length=100), nullable=True),
        sa.Column("airflow_run_id", sa.String(length=100), nullable=True),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "manual_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("submission_id", sa.String(length=100), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("period_label", sa.String(length=50), nullable=True),
        sa.Column("dropzone_path", sa.Text(), nullable=False),
        sa.Column("manifest_path", sa.Text(), nullable=True),
        sa.Column("original_file_name", sa.Text(), nullable=True),
        sa.Column("submitted_by", sa.String(length=100), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "ACCEPTED",
                "REJECTED",
                "DUPLICATED",
                "FAILED",
                name="submissionstatus",
            ),
            nullable=False,
        ),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("processed_run_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["processed_run_id"],
            ["ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id"),
    )
    op.create_table(
        "raw_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("period_label", sa.String(length=50), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("version_timestamp", sa.DateTime(), nullable=False),
        sa.Column("storage_backend", sa.String(length=50), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("original_file_name", sa.Text(), nullable=False),
        sa.Column("file_extension", sa.String(length=20), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.String(length=100), nullable=True),
        sa.Column(
            "ingestion_mode",
            sa.Enum("MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode"),
            nullable=False,
        ),
        sa.Column("is_latest_for_period", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_raw_assets_checksum", "raw_assets", ["checksum_sha256"], unique=False)
    op.create_index(
        "idx_raw_assets_latest",
        "raw_assets",
        ["product_id", "source_id", "period_label", "is_latest_for_period"],
        unique=False,
    )
    op.create_index(
        "idx_raw_assets_product_source_period",
        "raw_assets",
        ["product_id", "source_id", "period_label"],
        unique=False,
    )
    op.create_index(
        "idx_raw_assets_unique_version",
        "raw_assets",
        ["product_id", "source_id", "period_label", "version_number"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_raw_assets_unique_version", table_name="raw_assets")
    op.drop_index("idx_raw_assets_product_source_period", table_name="raw_assets")
    op.drop_index("idx_raw_assets_latest", table_name="raw_assets")
    op.drop_index("idx_raw_assets_checksum", table_name="raw_assets")
    op.drop_table("raw_assets")
    op.drop_table("manual_submissions")
    op.drop_table("ingestion_runs")
    op.drop_index("idx_sources_product_key", table_name="sources")
    op.drop_table("sources")
    op.drop_table("products")
    # ### end Alembic commands ###
