"""refactor: nuevo esquema de metadatos

Revision ID: 79cb92f10975
Revises: 0e8b8b1a6e04
Create Date: 2026-06-24 15:17:32.277963

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79cb92f10975"
down_revision: Union[str, None] = "0e8b8b1a6e04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre_corto", sa.String(length=100), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("fuente", sa.Text(), nullable=True),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("periodicidad", sa.Text(), nullable=True),
        sa.Column("desagregacion_geografica", sa.Text(), nullable=True),
        sa.Column("inicio_cobertura_temporal", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre_corto"),
    )
    op.create_table(
        "distribuciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column(
            "tipo_de_acceso",
            postgresql.ENUM(
                "MANUAL_UPLOAD", "HTTP_FILE", "API_JSON", name="sourcetype", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("manual_upload_allowed", sa.Boolean(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_distribuciones_dataset_nombre", "distribuciones", ["dataset_id", "nombre"], unique=True
    )
    op.create_table(
        "ingestion_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distribucion_id", sa.Integer(), nullable=False),
        sa.Column("extractor_class", sa.String(length=100), nullable=False),
        sa.Column(
            "period_type",
            postgresql.ENUM(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "YEARLY",
                "CUSTOM",
                name="periodtype",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "ingestion_mode",
            postgresql.ENUM(
                "MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("expected_file_types", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("schedule", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribucion_id"],
            ["distribuciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ingestions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=100), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("distribucion_id", sa.Integer(), nullable=False),
        sa.Column("period_label", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "DUPLICATED",
                "REJECTED",
                "PARTIAL",
                name="runstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            postgresql.ENUM(
                "SCHEDULED",
                "MANUAL_AIRFLOW",
                "MANUAL_DROPZONE",
                "MANUAL_CLI",
                "BACKFILL",
                "RETRY",
                name="triggertype",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "ingestion_mode",
            postgresql.ENUM(
                "MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("nombre_archivo", sa.Text(), nullable=True),
        sa.Column("dropzone_path", sa.Text(), nullable=True),
        sa.Column("manifest_path", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("orchestrator_name", sa.String(length=100), nullable=True),
        sa.Column("orchestrator_flow_id", sa.String(length=100), nullable=True),
        sa.Column("orchestrator_run_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["distribucion_id"],
            ["distribuciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "archivos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ingestion_id", sa.Integer(), nullable=False),
        sa.Column("distribucion_id", sa.Integer(), nullable=False),
        sa.Column("nombre_archivo", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("hash_sha256", sa.String(length=64), nullable=False),
        sa.Column("period_label", sa.String(length=50), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("version_timestamp", sa.DateTime(), nullable=False),
        sa.Column("is_latest_for_period", sa.Boolean(), nullable=False),
        sa.Column("storage_backend", sa.String(length=50), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("file_extension", sa.String(length=20), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.String(length=100), nullable=True),
        sa.Column(
            "ingestion_mode",
            postgresql.ENUM(
                "MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("fecha_ingesta", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribucion_id"],
            ["distribuciones.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_id"],
            ["ingestions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_archivos_hash", "archivos", ["hash_sha256"], unique=False)
    op.create_index(
        "idx_archivos_latest",
        "archivos",
        ["distribucion_id", "period_label", "is_latest_for_period"],
        unique=False,
    )
    op.create_index("idx_archivos_period", "archivos", ["period_label"], unique=False)
    op.create_index(
        "idx_archivos_unique_version",
        "archivos",
        ["distribucion_id", "period_label", "version_number"],
        unique=True,
    )
    op.drop_index(op.f("idx_raw_assets_checksum"), table_name="raw_assets")
    op.drop_index(op.f("idx_raw_assets_latest"), table_name="raw_assets")
    op.drop_index(op.f("idx_raw_assets_product_source_period"), table_name="raw_assets")
    op.drop_index(op.f("idx_raw_assets_unique_version"), table_name="raw_assets")
    op.drop_table("raw_assets")
    op.drop_table("manual_submissions")
    op.drop_table("ingestion_runs")
    op.drop_index(op.f("idx_sources_product_key"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("products")
    op.execute("DROP TYPE IF EXISTS submissionstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE submissionstatus AS ENUM ('PENDING', 'PROCESSING', 'ACCEPTED', 'REJECTED', 'DUPLICATED', 'FAILED')"
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source_key", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "source_type",
            postgresql.ENUM(
                "MANUAL_UPLOAD", "HTTP_FILE", "API_JSON", name="sourcetype", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ingestion_mode",
            postgresql.ENUM(
                "MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("manual_upload_allowed", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("requires_manifest", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "expected_file_types",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "period_type",
            postgresql.ENUM(
                "DAILY",
                "WEEKLY",
                "MONTHLY",
                "QUARTERLY",
                "YEARLY",
                "CUSTOM",
                name="periodtype",
                create_type=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("schedule", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("sources_product_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sources_pkey")),
    )
    op.create_index(
        op.f("idx_sources_product_key"), "sources", ["product_id", "source_key"], unique=True
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("run_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("period_label", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "DUPLICATED",
                "REJECTED",
                "PARTIAL",
                name="runstatus",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ingestion_mode",
            postgresql.ENUM(
                "MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            postgresql.ENUM(
                "SCHEDULED",
                "MANUAL_AIRFLOW",
                "MANUAL_DROPZONE",
                "MANUAL_CLI",
                "BACKFILL",
                "RETRY",
                name="triggertype",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("started_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("finished_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("airflow_dag_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("airflow_run_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("created_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("ingestion_runs_product_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("ingestion_runs_source_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("ingestion_runs_pkey")),
        sa.UniqueConstraint(
            "run_id",
            name=op.f("ingestion_runs_run_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "manual_submissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("submission_id", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("source_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("period_label", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("dropzone_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("manifest_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("original_file_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("submitted_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("submitted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "PROCESSING",
                "ACCEPTED",
                "REJECTED",
                "DUPLICATED",
                "FAILED",
                name="submissionstatus",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("review_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("processed_run_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["processed_run_id"],
            ["ingestion_runs.id"],
            name=op.f("manual_submissions_processed_run_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("manual_submissions_product_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("manual_submissions_source_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("manual_submissions_pkey")),
        sa.UniqueConstraint(
            "submission_id",
            name=op.f("manual_submissions_submission_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("product_key", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("owner_area", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("owner_person", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
        sa.UniqueConstraint(
            "product_key",
            name=op.f("products_product_key_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "raw_assets",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("period_label", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("version_number", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("version_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("storage_backend", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("storage_path", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("original_file_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("file_extension", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column("mime_type", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("file_size_bytes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("checksum_sha256", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("source_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("uploaded_by", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column(
            "ingestion_mode",
            postgresql.ENUM(
                "MANUAL", "AUTOMATED", "HYBRID", name="ingestionmode", create_type=False
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_latest_for_period", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["products.id"], name=op.f("raw_assets_product_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["ingestion_runs.id"], name=op.f("raw_assets_run_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("raw_assets_source_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("raw_assets_pkey")),
    )
    op.create_index(
        op.f("idx_raw_assets_unique_version"),
        "raw_assets",
        ["product_id", "source_id", "period_label", "version_number"],
        unique=True,
    )
    op.create_index(
        op.f("idx_raw_assets_product_source_period"),
        "raw_assets",
        ["product_id", "source_id", "period_label"],
        unique=False,
    )
    op.create_index(
        op.f("idx_raw_assets_latest"),
        "raw_assets",
        ["product_id", "source_id", "period_label", "is_latest_for_period"],
        unique=False,
    )
    op.create_index(
        op.f("idx_raw_assets_checksum"), "raw_assets", ["checksum_sha256"], unique=False
    )
    op.drop_index("idx_archivos_unique_version", table_name="archivos")
    op.drop_index("idx_archivos_period", table_name="archivos")
    op.drop_index("idx_archivos_latest", table_name="archivos")
    op.drop_index("idx_archivos_hash", table_name="archivos")
    op.drop_table("archivos")
    op.drop_table("ingestions")
    op.drop_table("ingestion_configs")
    op.drop_index("idx_distribuciones_dataset_nombre", table_name="distribuciones")
    op.drop_table("distribuciones")
    op.drop_table("datasets")
    # ### end Alembic commands ###
