"""feat: add RecursoDatos and ArchivoRecurso

Revision ID: f525df572702
Revises: 79cb92f10975
Create Date: 2026-06-25 16:16:41.623844

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f525df572702"
down_revision: Union[str, None] = "79cb92f10975"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurso_datos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("distribucion_id", sa.Integer(), nullable=False),
        sa.Column("recurso_key", sa.String(length=100), nullable=False),
        sa.Column("nombre", sa.Text(), nullable=False),
        sa.Column("descripcion", sa.Text(), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["distribucion_id"],
            ["distribuciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_recurso_datos_distribucion_key",
        "recurso_datos",
        ["distribucion_id", "recurso_key"],
        unique=True,
    )
    op.create_table(
        "archivo_recurso",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archivo_id", sa.Integer(), nullable=False),
        sa.Column("recurso_datos_id", sa.Integer(), nullable=False),
        sa.Column(
            "locator_type",
            sa.Enum("ROOT", "SHEET", "MEMBER", "JSON_PATH", "XPATH", name="locatortype"),
            nullable=False,
        ),
        sa.Column("locator_value", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archivo_id"],
            ["archivos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recurso_datos_id"],
            ["recurso_datos.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_archivo_recurso_unique",
        "archivo_recurso",
        ["archivo_id", "recurso_datos_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_archivo_recurso_unique", table_name="archivo_recurso")
    op.drop_table("archivo_recurso")
    op.drop_index("idx_recurso_datos_distribucion_key", table_name="recurso_datos")
    op.drop_table("recurso_datos")
    # ### end Alembic commands ###
